### ISSUE TITLE
What version of tibco client?

### ISSUE THREAD

**Issue by brunnels** [zyclonite/php-tibems#1]
What Tibco EMS client version have you tested/developed against?

I got your extension to compile against Tibco EMS 7.0.1l and php 5.5.8 by updating tibco.c "function_entry" to be "zend_function_entry".

I can successfully connect, disconnect, and recvmsg from a tibco queue but I'm getting "tibco_sendmsg(): Error creating tibemsMsgProducer" when trying to use sendmsg.

I checked the docs and the syntax looks correct for tibemsSession_CreateProducer so all I can guess is that there is some other difference in the latest version and the version you developed against.

Any assistance or suggestions on troubleshooting the issue would be appreciated.

**Comment by zyclonite** [comment]
the last changes were made nearly 5 years ago... so i guess it was around version 5.x
i will take a look what has changed

**Comment by zyclonite** [comment]
tested it after my update with tibco 7.0.1 and php 5.4.17 (should work with 5.5 too) and it works
maybe it was a permission problem

the changes i made only affected the compilation...

**Comment by brunnels** [comment]
Wish there were some easy way to debug what is going on.  The code looks like it should be returning the status that tibemsSession_CreateProducer is returning as part of the error message but all I get is:

Fatal error: tibco_sendmsg(): Error creating tibemsMsgProducer

**Comment by zyclonite** [comment]
can you get me a code snippet of your sending script and what is configured (of relevance) on the tibco side, so i can try to reproduce it

**Comment by brunnels** [comment]
Okay, I found the issue.

tibco_sendmsg(string destination, string message [, topic bool false]);

Docs showed topic as optional default to false.  If I call without I get the error.  If I set false it works.

ERROR: tibco_sendmsg('.alarmpoint_150095.Change', $this->createChangeMessage());
WORKS: tibco_sendmsg('.alarmpoint_150095.Change', $this->createChangeMessage(), false);

**Comment by zyclonite** [comment]
great :+1:

**Comment by brunnels** [comment]
Can you explain the connection options for setting up the connection via SSL?  I'm connecting to a development system now and it doesn't require username or password.  The UAT and Production systems will require SSL certificates to connect but no username or password.

**Comment by zyclonite** [comment]
ssl was never implemented ...
if you like you can do so and send me a pull request

**Comment by brunnels** [comment]
Okay, this had me thinking it had.  Probably have the make the $ssl string parameter an array instead with the ssl parameters the tibco client requires.

tibco_connect(string server, string user, string pass [, string ssl]);
  Connects to Tibco EMS Server (ssl)
